name: CD Release Pipeline

# Only run when code lands on main
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build & Upload Release JAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build without running tests
      - name: Package Application (skip tests)
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-jar
          path: target/*.jar

